### ISSUE TITLE
Mouse.java: normalize() can be optimized

### ISSUE THREAD

**Issue by DispatchCode** [yapeteam/Minecraft-1.8.9-lwjgl3#1]
https://github.com/TIMER-err/Minecraft-1.8.9-lwjgl3/blob/15eaa8906f1e2d9da927a102687032477d12f8f9/src/org/lwjglx/input/Mouse.java#L243C1-L246C6

The above function can be changed with:

```
private static int normalize(int input) {
      return Math.abs(input);
}
```

**Comment by ChristopherProject** [comment]
Thanks Marco for providing this optimization ^^
